server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://localhost:8999
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    limits:
        default_items: 10
        max_items: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: 'Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: TinyDB
        connection: /tmp/registration-api-process-manager.db
        output_dir: /tmp/

logging:
    level: DEBUG
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: pygeoapi HEIF demo
        description: pygeoapi HEIF demo
        keywords:
            - HEIF
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0
        url: https://pygeoapi.io
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0
    provider:
        name: OSGeo
        url: https://osgeo.org
    contact:
        name: Kralidis, Tom
        position: staff
        address: 4905 Dufferin Street
        city: Toronto
        stateorprovince: Ontario
        postalcode: M3H 5T4
        country: Canada
        phone: null
        fax: null
        email: you@example.org
        url: https://kralidis.ca
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact

resources:
    obs:
        type: collection
        title: Observations
        description: My cool observations
        keywords:
            - observations
            - monitoring
        linked-data:
            context:
                - datetime: https://schema.org/DateTime
                - vocab: https://example.com/vocab#
                  stn_id: "vocab:stn_id"
                  value: "vocab:value"
        links:
            - type: text/csv
              rel: canonical
              title: data
              href: https://github.com/mapserver/mapserver/blob/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
            - type: text/csv
              rel: alternate
              title: data
              href: https://raw.githubusercontent.com/mapserver/mapserver/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2000-10-30T18:24:39Z
                end: 2007-10-30T08:57:29Z
        providers:
            - type: feature
              name: CSV
              data: /pygeoapi/tests/data/obs.csv
              id_field: id
              geometry:
                  x_field: long
                  y_field: lat

    heif-demo:
        type: collection
        title: HEIF demo
        description: HEIF demo
        keywords:
            - HEIF
            - demo
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://github.com/opengeospatial/developer-events/wiki/2026-Joint-OGC-%E2%80%93-OSGeo-%E2%80%93-ASF-Code-Sprint
              hreflang: en-US
        extents:
            spatial: &pspatial
                bbox: [138.494192, -34.804844, 138.498669, -34.800998]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: map
              name: pygeoapi.provider.heifmap.HEIFMapProvider
              data: /data/tb21-single-image-hevc.heif
              format:
                    name: png
                    mimetype: image/png
              options: *pspatial
